### ISSUE TITLE
Scheduled Tasks

### ISSUE THREAD

**Issue by tinect** [FriendsOfShopware/shopmon#21]
### Actual behaviour

See red status for tasks, because they were never checked again

### Expected behaviour

the status should be checked more often

### Steps to Reproduce?

add shop check scheduled tasks....

it is 18:37, last checked 15:46:35
![image](https://user-images.githubusercontent.com/135993/188280040-3456ec21-2a00-49cb-8c14-6cb23492d38d.png)

**Comment by shyim** [comment]
It should be checked every hour 🤔

**Comment by tinect** [comment]
> It should be checked every hour 🤔

AND compared with "last checked at", not current time
