### ISSUE TITLE
Shopware compatibility on extension overview

### ISSUE THREAD

**Issue by wannevancamp** [FriendsOfShopware/shopmon#300]
### Please describe the feature you would like to see implemented.

When performing a Shopware upgrade (audit), we need to manually validate each plugin in the Shopware store for compatibility with the newer Shopware version. 

It would be helpful if we could get an overview of the compatible Shopware versions in Shopmon on the Extension overview.

![image](https://github.com/FriendsOfShopware/shopmon/assets/3399877/0fed3c9c-d7e0-4d72-81bc-fd091406ea79)

**Comment by pumpi** [comment]
This function already exists. Click the button "Compatibility Check" near the Shopware version 
![image](https://github.com/FriendsOfShopware/shopmon/assets/412142/5503bcc5-6ba5-40e8-abed-2826b334236c)

After Click you can select your Shopware version you want to update
![image](https://github.com/FriendsOfShopware/shopmon/assets/412142/48bc3778-cae7-4446-ad76-423003ce9c42)

**Comment by wannevancamp** [comment]
Wow didn't know that. Very cool feature!

Thanks 🙏
