### ISSUE TITLE
Shop Detail adjustments

### ISSUE THREAD

**Issue by shyim** [FriendsOfShopware/shopmon#35]
### Please describe the feature you would like to see implemented.

- [x] Show Admin URL
- [x] Show installation date of extensions
- [x] Add storelink to extension

**Comment by pumpi** [comment]
@shyim storelink for extensions not exists on my test shop

![Bildschirmfoto 2022-09-07 um 15 39 54](https://user-images.githubusercontent.com/412142/188892846-f774661c-ca3f-4f54-ba24-d612ed20caca.png)

**Comment by shyim** [comment]
done
