### ISSUE TITLE
Selfhosted worker

### ISSUE THREAD

**Issue by Isengo1989** [FriendsOfShopware/shopmon#64]
### Question

Currently it is possible to use selfhosted DB by planetscale but the api.toml is connected still with fos

Can it be switched to selfhosted cloudflare worker at ease or is there a migration process that has to take place?

**Comment by shyim** [comment]
You have to use wrangler secrets:put for any key and set them by own

**Comment by shyim** [comment]
https://developers.cloudflare.com/workers/wrangler/commands/#kvkey or using ui

**Comment by Isengo1989** [comment]
Ok, but basically it is possible to change the api.toml and add an own API account_id, routes etc.
